module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '😘', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💗'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/L21wT8us3gf8DS4fqbOIAy?mode=ems_copy_c👈?mode=ac_t',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/i4esg2.png',
    NEWSLETTER_JID: '120363420828095666@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: '*BELA MINI* ',
    OWNER_NAME: 'ꜰɪxᴏ xᴅ',
    OWNER_NUMBER: '94703945265',
    BOT_VERSION: '1.1.1',
    BOT_FOOTER: '> © ʙᴇʟᴀ ᴍɪɴɪ',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbAbJCO35fLy2OzH9y1I',
};
