module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🌸', '🪴', '💫', '🍂', '🌟','🫀', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://whatsapp.com/channel/0029VbAbJCO35fLy2OzH9y1I',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/i4esg2.png',
    NEWSLETTER_JID: '120363420828095666@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'ʙᴇʟᴀ-ᴍɪɴɪ',
    OWNER_NAME: 'ꜰɪxᴏ xᴅ',
    OWNER_NUMBER: '94703945265',
    BOT_VERSION: '1.0.2',
    BOT_FOOTER: '> ᴘᴏᴡᴇʀᴇᴅ ʙʏ ꜰɪxᴏ xᴅ.',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbAbJCO35fLy2OzH9y1I',
};
